from board_game import GameBoard
from individual import Individual
from board_game import GameBoard

tabuleiro = GameBoard(12)
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
