from individual import Individual

tabuleiro = Individual(12)
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
tabuleiro.player_move(1)
tabuleiro.win()
print(tabuleiro)
